#############################################################################
# Makefile for building: CanYin_Client
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  CanYin_Client.pro
# Template: app
# Command: E:/Qt/bin/5.3/mingw482_32/bin/qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile CanYin_Client.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = E:/Qt/bin/5.3/mingw482_32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = cp -f
INSTALL_PROGRAM = cp -f
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: CanYin_Client.pro ../../bin/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf ../../bin/5.3/mingw482_32/mkspecs/features/spec_pre.prf \
		../../bin/5.3/mingw482_32/mkspecs/qdevice.pri \
		../../bin/5.3/mingw482_32/mkspecs/features/device_config.prf \
		../../bin/5.3/mingw482_32/mkspecs/common/shell-unix.conf \
		../../bin/5.3/mingw482_32/mkspecs/qconfig.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../bin/5.3/mingw482_32/mkspecs/features/qt_functions.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/qt_config.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf \
		../../bin/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf \
		../../bin/5.3/mingw482_32/mkspecs/features/spec_post.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/default_pre.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf \
		YF/YF.pri \
		../../bin/5.3/mingw482_32/mkspecs/features/resolve_config.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/default_post.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/win32/rtti.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/precompile_header.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/warn_on.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/qt.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/resources.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/moc.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/win32/opengl.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/uic.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/win32/windows.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/testcase_targets.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/exceptions.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/yacc.prf \
		../../bin/5.3/mingw482_32/mkspecs/features/lex.prf \
		CanYin_Client.pro \
		E:/Qt/bin/5.3/mingw482_32/lib/qtmaind.prl \
		E:/Qt/bin/5.3/mingw482_32/lib/Qt5Cored.prl \
		E:/Qt/bin/5.3/mingw482_32/lib/Qt5Widgets.prl \
		E:/Qt/bin/5.3/mingw482_32/lib/Qt5Sql.prl \
		E:/Qt/bin/5.3/mingw482_32/lib/Qt5Network.prl \
		E:/Qt/bin/5.3/mingw482_32/lib/Qt5Gui.prl \
		E:/Qt/bin/5.3/mingw482_32/lib/Qt5Core.prl
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile CanYin_Client.pro
../../bin/5.3/mingw482_32/mkspecs/features/spec_pre.prf:
../../bin/5.3/mingw482_32/mkspecs/qdevice.pri:
../../bin/5.3/mingw482_32/mkspecs/features/device_config.prf:
../../bin/5.3/mingw482_32/mkspecs/common/shell-unix.conf:
../../bin/5.3/mingw482_32/mkspecs/qconfig.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axbase_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_axserver_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_clucene_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_concurrent_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_core.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_core_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_declarative_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_designer.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_designer_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_enginio_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_gui.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_gui_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_help.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_help_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimedia_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_network.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_network_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_nfc_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_opengl_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_positioning_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_printsupport_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qml.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qml_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qmltest_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quick.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quick_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_script.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_script_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_scripttools_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sensors_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_serialport_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sql.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_sql_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_svg.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_svg_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_testlib_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_uitools_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkit_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_websockets_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_widgets_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_winextras_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xml.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xml_private.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../bin/5.3/mingw482_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../bin/5.3/mingw482_32/mkspecs/features/qt_functions.prf:
../../bin/5.3/mingw482_32/mkspecs/features/qt_config.prf:
../../bin/5.3/mingw482_32/mkspecs/features/win32/qt_config.prf:
../../bin/5.3/mingw482_32/mkspecs/win32-g++/qmake.conf:
../../bin/5.3/mingw482_32/mkspecs/features/spec_post.prf:
../../bin/5.3/mingw482_32/mkspecs/features/exclusive_builds.prf:
../../bin/5.3/mingw482_32/mkspecs/features/default_pre.prf:
../../bin/5.3/mingw482_32/mkspecs/features/win32/default_pre.prf:
YF/YF.pri:
../../bin/5.3/mingw482_32/mkspecs/features/resolve_config.prf:
../../bin/5.3/mingw482_32/mkspecs/features/exclusive_builds_post.prf:
../../bin/5.3/mingw482_32/mkspecs/features/default_post.prf:
../../bin/5.3/mingw482_32/mkspecs/features/win32/rtti.prf:
../../bin/5.3/mingw482_32/mkspecs/features/precompile_header.prf:
../../bin/5.3/mingw482_32/mkspecs/features/warn_on.prf:
../../bin/5.3/mingw482_32/mkspecs/features/qt.prf:
../../bin/5.3/mingw482_32/mkspecs/features/resources.prf:
../../bin/5.3/mingw482_32/mkspecs/features/moc.prf:
../../bin/5.3/mingw482_32/mkspecs/features/win32/opengl.prf:
../../bin/5.3/mingw482_32/mkspecs/features/uic.prf:
../../bin/5.3/mingw482_32/mkspecs/features/win32/windows.prf:
../../bin/5.3/mingw482_32/mkspecs/features/testcase_targets.prf:
../../bin/5.3/mingw482_32/mkspecs/features/exceptions.prf:
../../bin/5.3/mingw482_32/mkspecs/features/yacc.prf:
../../bin/5.3/mingw482_32/mkspecs/features/lex.prf:
CanYin_Client.pro:
E:/Qt/bin/5.3/mingw482_32/lib/qtmaind.prl:
E:/Qt/bin/5.3/mingw482_32/lib/Qt5Cored.prl:
E:/Qt/bin/5.3/mingw482_32/lib/Qt5Widgets.prl:
E:/Qt/bin/5.3/mingw482_32/lib/Qt5Sql.prl:
E:/Qt/bin/5.3/mingw482_32/lib/Qt5Network.prl:
E:/Qt/bin/5.3/mingw482_32/lib/Qt5Gui.prl:
E:/Qt/bin/5.3/mingw482_32/lib/Qt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile CanYin_Client.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
